server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://nvcnexrtaurmyz:6c1bff86f81fa0dcde7e827191d3b8058d82f594ed96110f467a33f95a749260@ec2-35-170-85-206.compute-1.amazonaws.com:5432/d1o1t0sgvhfok5
    username: nvcnexrtaurmyz
    password: 6c1bff86f81fa0dcde7e827191d3b8058d82f594ed96110f467a33f95a749260
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para a Santander Dev Week da DIO / Backend
  version: 2.0
